# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46f53da38d9246bd5598cf765b37f3d89393177d78db755e5c1e6d40e9c4a451b62d9812ebf873dfbb881504e7f34045f79a5d088837703001a1c1c1cdbe96be

test:
  secret_key_base: 7f31153089bd2ab97bea0bdf0bca26dd33edb42a7da37f158a9902c47db858241f1bcd2f7534a614f6ee6d11d96a821d9509a5851fd2f249120bbd72fc01c784

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
