# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 314d2335a2734c41b20a4a771bc903be335b5d3ce1862f914b8d25aa64653ea93bb0a2cf3a3beaf55983c1610fad030580f424990cba85c06e419bb4a89f583e

test:
  secret_key_base: d00136a7ce3b2d027d386eb8f289a08c13bf174699dedbea070b891b977e838f19a832e63f26686da9a82964f1f28f240b4a6640648514e3603f45c1dbfc6edd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
